yarnPath: .yarn/releases/yarn-3.2.0.cjs

nodeLinker: node-modules

packageExtensions:
  '@xstate/tools-shared@*':
    peerDependencies:
      '@babel/core': '*'
  '@xstate/cli@*':
    peerDependencies:
      'prettier': '*'
  '@mdx-js/loader@*':
    peerDependencies:
      'react': '*'
  'eslint-config-airbnb-typescript@*':
    peerDependencies:
      'eslint': '*'
      'eslint-plugin-import': '*'
  '@storybook/addon-postcss@*':
    peerDependencies:
      'webpack': '*'
  'graphql-config@*':
    peerDependencies:
      '@types/node': '*'
      'typescript': '*'
  '@graphql-codegen/cli@*':
    peerDependencies:
      '@types/node': '*'
      'typescript': '*'
