export const ipcEvents = {
  STORE_GET_ALL: 'STORE_GET_ALL',
  STORE_GET_KEY: 'STORE_GET_KEY',
  STORE_SET_ALL: 'STORE_SET_ALL',
  STORE_SET_KEY: 'STORE_SET_KEY',
  STORE_RESET_KEY: 'STORE_RESET_KEY',
  LOG_ING: 'LOG_IN',
  GET_USER: 'GET_USER',
  LOG_OUT: 'LOG_OUT',
};
