export const ipcEvents = {
  CLIENT_STORE_GET_ALL: 'STORE_GET_ALL',
  CLIENT_STORE_GET_KEY: 'STORE_GET_KEY',
  STORE_SET_ALL: 'STORE_SET_ALL',
  CLIENT_STORE_SET_KEY: 'STORE_SET_KEY',
  CLIENT_STORE_RESET_KEY: 'STORE_RESET_KEY',
  LOGIN: 'LOG_IN',
  LOGOUT: 'LOG_OUT',
  GET_USER: 'GET_USER',
  SS_READ: 'SS_READ',
  SS_UPDATE: 'SS_UPDATE',
};
