name: Visual Regression Tests

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: addnab/docker-run-action@v2
        with:
          image: backstopjs/backstopjs:5.1.0
          options: --mount type=bind,source=${{ github.workspace }},target=/src -it
          run: |
            test "--config=tooling/backstop/json" "--moby"
